version: '3.1'

services:
  mysql:
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - '3306:3306'
    deploy:


  app:
    ports:
      - 80:5000
    build: .
    depends_on:
      - mysql
    deploy:

